//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DPM_Api_VBETA.webService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DynmixProcessMangWS_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS")]
    public partial class DynmixProcessMangWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListeConsultantOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListeClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteConsultantOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddConsultantOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectConsuOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateConsuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DynmixProcessMangWS() {
            this.Url = global::DPM_Api_VBETA.Properties.Settings.Default.DPM_Api_VBETA_webService_DynmixProcessMangWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListeConsultantCompletedEventHandler ListeConsultantCompleted;
        
        /// <remarks/>
        public event ListeClientCompletedEventHandler ListeClientCompleted;
        
        /// <remarks/>
        public event DeleteConsultantCompletedEventHandler DeleteConsultantCompleted;
        
        /// <remarks/>
        public event AddConsultantCompletedEventHandler AddConsultantCompleted;
        
        /// <remarks/>
        public event SelectConsuCompletedEventHandler SelectConsuCompleted;
        
        /// <remarks/>
        public event UpdateConsuCompletedEventHandler UpdateConsuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS:ListeConsultant", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", ResponseElementName="ListeConsultant_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ListeConsultant(ref RootCons consultant) {
            object[] results = this.Invoke("ListeConsultant", new object[] {
                        consultant});
            consultant = ((RootCons)(results[0]));
        }
        
        /// <remarks/>
        public void ListeConsultantAsync(RootCons consultant) {
            this.ListeConsultantAsync(consultant, null);
        }
        
        /// <remarks/>
        public void ListeConsultantAsync(RootCons consultant, object userState) {
            if ((this.ListeConsultantOperationCompleted == null)) {
                this.ListeConsultantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListeConsultantOperationCompleted);
            }
            this.InvokeAsync("ListeConsultant", new object[] {
                        consultant}, this.ListeConsultantOperationCompleted, userState);
        }
        
        private void OnListeConsultantOperationCompleted(object arg) {
            if ((this.ListeConsultantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListeConsultantCompleted(this, new ListeConsultantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS:ListeClient", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", ResponseElementName="ListeClient_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ListeClient(ref Root xmlportCust) {
            object[] results = this.Invoke("ListeClient", new object[] {
                        xmlportCust});
            xmlportCust = ((Root)(results[0]));
        }
        
        /// <remarks/>
        public void ListeClientAsync(Root xmlportCust) {
            this.ListeClientAsync(xmlportCust, null);
        }
        
        /// <remarks/>
        public void ListeClientAsync(Root xmlportCust, object userState) {
            if ((this.ListeClientOperationCompleted == null)) {
                this.ListeClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListeClientOperationCompleted);
            }
            this.InvokeAsync("ListeClient", new object[] {
                        xmlportCust}, this.ListeClientOperationCompleted, userState);
        }
        
        private void OnListeClientOperationCompleted(object arg) {
            if ((this.ListeClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListeClientCompleted(this, new ListeClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS:DeleteConsultant", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", ResponseElementName="DeleteConsultant_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool DeleteConsultant(ref int id) {
            object[] results = this.Invoke("DeleteConsultant", new object[] {
                        id});
            id = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteConsultantAsync(int id) {
            this.DeleteConsultantAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteConsultantAsync(int id, object userState) {
            if ((this.DeleteConsultantOperationCompleted == null)) {
                this.DeleteConsultantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteConsultantOperationCompleted);
            }
            this.InvokeAsync("DeleteConsultant", new object[] {
                        id}, this.DeleteConsultantOperationCompleted, userState);
        }
        
        private void OnDeleteConsultantOperationCompleted(object arg) {
            if ((this.DeleteConsultantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteConsultantCompleted(this, new DeleteConsultantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS:AddConsultant", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", ResponseElementName="AddConsultant_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool AddConsultant(string cin, string nom, string prenom) {
            object[] results = this.Invoke("AddConsultant", new object[] {
                        cin,
                        nom,
                        prenom});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddConsultantAsync(string cin, string nom, string prenom) {
            this.AddConsultantAsync(cin, nom, prenom, null);
        }
        
        /// <remarks/>
        public void AddConsultantAsync(string cin, string nom, string prenom, object userState) {
            if ((this.AddConsultantOperationCompleted == null)) {
                this.AddConsultantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddConsultantOperationCompleted);
            }
            this.InvokeAsync("AddConsultant", new object[] {
                        cin,
                        nom,
                        prenom}, this.AddConsultantOperationCompleted, userState);
        }
        
        private void OnAddConsultantOperationCompleted(object arg) {
            if ((this.AddConsultantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddConsultantCompleted(this, new AddConsultantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS:SelectConsu", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", ResponseElementName="SelectConsu_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SelectConsu(ref RootCons xmlConsult, int id) {
            object[] results = this.Invoke("SelectConsu", new object[] {
                        xmlConsult,
                        id});
            xmlConsult = ((RootCons)(results[0]));
        }
        
        /// <remarks/>
        public void SelectConsuAsync(RootCons xmlConsult, int id) {
            this.SelectConsuAsync(xmlConsult, id, null);
        }
        
        /// <remarks/>
        public void SelectConsuAsync(RootCons xmlConsult, int id, object userState) {
            if ((this.SelectConsuOperationCompleted == null)) {
                this.SelectConsuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectConsuOperationCompleted);
            }
            this.InvokeAsync("SelectConsu", new object[] {
                        xmlConsult,
                        id}, this.SelectConsuOperationCompleted, userState);
        }
        
        private void OnSelectConsuOperationCompleted(object arg) {
            if ((this.SelectConsuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectConsuCompleted(this, new SelectConsuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS:UpdateConsu", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", ResponseElementName="UpdateConsu_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/DynmixProcessMangWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool UpdateConsu(int idConsu, string nom, string prenom) {
            object[] results = this.Invoke("UpdateConsu", new object[] {
                        idConsu,
                        nom,
                        prenom});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateConsuAsync(int idConsu, string nom, string prenom) {
            this.UpdateConsuAsync(idConsu, nom, prenom, null);
        }
        
        /// <remarks/>
        public void UpdateConsuAsync(int idConsu, string nom, string prenom, object userState) {
            if ((this.UpdateConsuOperationCompleted == null)) {
                this.UpdateConsuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateConsuOperationCompleted);
            }
            this.InvokeAsync("UpdateConsu", new object[] {
                        idConsu,
                        nom,
                        prenom}, this.UpdateConsuOperationCompleted, userState);
        }
        
        private void OnUpdateConsuOperationCompleted(object arg) {
            if ((this.UpdateConsuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateConsuCompleted(this, new UpdateConsuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50004")]
    public partial class RootCons {
        
        private RecCons[] recConsField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecCons")]
        public RecCons[] RecCons {
            get {
                return this.recConsField;
            }
            set {
                this.recConsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50004")]
    public partial class RecCons {
        
        private string cinField;
        
        private string nomField;
        
        private string prenomField;
        
        private int idField;
        
        public RecCons() {
            this.idField = 0;
        }
        
        /// <remarks/>
        public string cin {
            get {
                return this.cinField;
            }
            set {
                this.cinField = value;
            }
        }
        
        /// <remarks/>
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
            }
        }
        
        /// <remarks/>
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                this.prenomField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class RecG18 {
        
        private string noField;
        
        private string nameField;
        
        private string adresseField;
        
        private string phoneField;
        
        private string lastDateModField;
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string LastDateMod {
            get {
                return this.lastDateModField;
            }
            set {
                this.lastDateModField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class Root {
        
        private RecG18[] recG18Field;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecG18")]
        public RecG18[] RecG18 {
            get {
                return this.recG18Field;
            }
            set {
                this.recG18Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ListeConsultantCompletedEventHandler(object sender, ListeConsultantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListeConsultantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListeConsultantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RootCons consultant {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RootCons)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ListeClientCompletedEventHandler(object sender, ListeClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListeClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListeClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Root xmlportCust {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DeleteConsultantCompletedEventHandler(object sender, DeleteConsultantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteConsultantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteConsultantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AddConsultantCompletedEventHandler(object sender, AddConsultantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddConsultantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddConsultantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SelectConsuCompletedEventHandler(object sender, SelectConsuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectConsuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectConsuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RootCons xmlConsult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RootCons)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateConsuCompletedEventHandler(object sender, UpdateConsuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateConsuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateConsuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591